### ISSUE TITLE
Code snippets inside Doxygen comments cause failure of Breathe 4.7.0

### ISSUE THREAD

**Issue by krzychb** [michaeljones/breathe#344]
Hi Breathe Users and Maintainers,

After upgrade from Breathe release 4.6.0 to 4.7.0 I am getting the following error during documentation build:

```
Exception occurred:
  File "C:/msys32/mingw32/lib/python2.7/site-packages/breathe/renderer/sphinxrenderer.py", line 206, in get_domain
    if isinstance(node, six.text_type) or node.node_type == "enumvalue":
AttributeError: 'str' object has no attribute 'node_type'
The full traceback has been saved in c:/users/user-name/appdata/local/temp/sphinx-err-3z4ilr.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [Makefile:20: html] Error 1
```
I have traced it down to Doxygen in-line documentation of function that contains code snippets, e.g. https://github.com/krzychb/rtd-test-bed/blob/master/headers/nvs.h#L198-L255

A sample documentation presenting this function - https://github.com/krzychb/rtd-test-bed/blob/master/docs/case-code-snippet.rst

- Does anybody else have similar issue? 
- How to fix it (I assume in sphinxrenderer.py, line 206), so, I can keep snippets in documentation of individual functions?

**Comment by SylvainCorlay** [comment]
It appears to be a bug. `six.text_type` should probably be replaced by `six.string_types`.

It you can confirm this works for you, PRs are welcome!

**Comment by krzychb** [comment]
@SylvainCorlay, awesome, it works now!
Similar change was required also in line 1204.
I will prepare PR later today.
Thanks a lot :+1:

**Comment by SylvainCorlay** [comment]
4.7.1 out on pypi. Will be on conda-forge sometimes in the week end.

**Comment by SylvainCorlay** [comment]
Breathe 4.7.1 is out on conda-forge.
