### ISSUE TITLE
AttributeError: 'paragraph' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by emilydolson** [michaeljones/breathe#381]
Everything was working fine with v4.8.0, but with version 4.9.0 I get the following error when building docs on the master branch of the repo: https://github.com/devosoft/Empirical. An example failed build is here: https://readthedocs.org/projects/empirical/builds/7285857/. 

Sorry for not having a more minimal example.

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/sphinx/application.py", line 339, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 329, in build_update
    'out of date' % len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 342, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/sphinx/environment/__init__.py", line 601, in update
    self._read_serial(docnames, self.app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/sphinx/environment/__init__.py", line 621, in _read_serial
    self.read_doc(docname, app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/sphinx/environment/__init__.py", line 758, in read_doc
    pub.publish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/sphinx/io.py", line 74, in read
    self.parse()
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/docutils/parsers/rst/__init__.py", line 185, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2745, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 326, in section
    self.new_subsection(title, lineno, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 394, in new_subsection
    node=section_node, match_titles=True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2745, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 326, in section
    self.new_subsection(title, lineno, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 394, in new_subsection
    node=section_node, match_titles=True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2318, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2330, in explicit_construct
    return method(self, expmatch)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2073, in directive
    directive_class, match, type_name, option_presets)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2122, in run_directive
    result = directive_instance.run()
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/breathe/directive/file.py", line 91, in run
    return self.handle_contents(file_, project_info)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/breathe/directive/file.py", line 61, in handle_contents
    node_list.extend(object_renderer.render(node_stack[0], context))
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/breathe/renderer/sphinxrenderer.py", line 1302, in render
    result = method(self, node)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/breathe/renderer/sphinxrenderer.py", line 631, in visit_compounddef
    nodelist.extend(self.render_iterable(node.innernamespace))
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/breathe/renderer/sphinxrenderer.py", line 1312, in render_iterable
    output.extend(self.render(entry))
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/breathe/renderer/sphinxrenderer.py", line 1302, in render
    result = method(self, node)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/breathe/renderer/sphinxrenderer.py", line 907, in visit_ref
    return self.visit_compound(node, False, get_node_info=get_node_info)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/breathe/renderer/sphinxrenderer.py", line 468, in visit_compound
    rendered_data = self.render(file_data, parent_context)
Warning: Duplicate target detected: namespaceemp
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/breathe/renderer/sphinxrenderer.py", line 1302, in render
    result = method(self, node)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/breathe/renderer/sphinxrenderer.py", line 459, in visit_doxygendef
    return self.render(node.compounddef)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/breathe/renderer/sphinxrenderer.py", line 1302, in render
    result = method(self, node)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/breathe/renderer/sphinxrenderer.py", line 610, in visit_compounddef
    child_nodes = self.render(sectiondef)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/breathe/renderer/sphinxrenderer.py", line 1302, in render
    result = method(self, node)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/breathe/renderer/sphinxrenderer.py", line 644, in visit_sectiondef
    node_list.extend(self.render_iterable(node.memberdef))
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/breathe/renderer/sphinxrenderer.py", line 1312, in render_iterable
    output.extend(self.render(entry))
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/breathe/renderer/sphinxrenderer.py", line 1302, in render
    result = method(self, node)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/breathe/renderer/sphinxrenderer.py", line 1245, in dispatch_memberdef
    return self.visit_variable(node)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/breathe/renderer/sphinxrenderer.py", line 1109, in visit_variable
    return self.render_declaration(node, declaration, update_signature=update_signature)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/breathe/renderer/sphinxrenderer.py", line 417, in render_declaration
    update_signature(signode, obj_type)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/breathe/renderer/sphinxrenderer.py", line 1108, in update_signature
    self.update_signature_with_initializer(signature, node)
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/breathe/renderer/sphinxrenderer.py", line 1096, in update_signature_with_initializer
    if not nodes[0].startswith('='):
AttributeError: 'paragraph' object has no attribute 'startswith'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/empirical/envs/master/lib/python3.5/site-packages/breathe/renderer/sphinxrenderer.py", line 1096, in update_signature_with_initializer
    if not nodes[0].startswith('='):
AttributeError: 'paragraph' object has no attribute 'startswith'
```

**Comment by melvinvermeeren** [comment]
The only addition for 4.9.0 is #380, which renders newlines as paragraphs. I will investigate now.

**Comment by melvinvermeeren** [comment]
Initial finding is that it is calling `startswith` on `docutils.nodes.paragraph`, which of course does not work. The `nodes` passed to `update_signature_with_initializer` is a list with only paragraph types, in this case 10 of them.

The content of that list: `[<paragraph: <#text: '= {'>>, <paragraph: <#text: '    0, 1, 1, 2 ...'>>, <paragraph: <#text: '    1, 2, 2, 3 ...'>>, <paragraph: <#text: '    1, 2, 2, 3 ...'>>, <paragraph: <#text: '    2, 3, 3, 4 ...'>>, <paragraph: <#text: '    1, 2, 2, 3 ...'>>, <paragraph: <#text: '    2, 3, 3, 4 ...'>>, <paragraph: <#text: '    2, 3, 3, 4 ...'>>, <paragraph: <#text: '    3, 4, 4, 5 ...'>>, <paragraph: <#text: '  }'>>]`

---

As I am not yet very familiar with the Sphinx/Breathe stack I am not sure if the problem is that the paragraph type isn't handled properly or that this function should never be called with paragraph type nodes.

If I assume the previous code was correct then this bug would have actually happened in other edge cases with the `<linebreak>` tag. It seems that it simply went unnoticed with `<linebreak>`, but with `\n` we instantly hit this bug.

---

For now I will try to fix it by checking is the type is paragraph. and if so, try to apply the logic to the text type within the paragraph. Hopefully that will resolve the issue.

**Comment by melvinvermeeren** [comment]
@emilydolson 4.9.1 has been released just now and should fix this. Please confirm on your side too, thanks.

**Comment by emilydolson** [comment]
That fixed it! Thanks so much for the fast fix!
