### ISSUE TITLE
Sphinx 2 not supported?

### ISSUE THREAD

**Issue by sdebionne** [michaeljones/breathe#427]
Sphinx 2 was released on Conda a couple of days ago and it looks like there are some incompatibility with the latest version of breathe (v4.11.1). Here is what I get with a simple ` doxygenclass` directive:

```
Exception occurred:
  File "/opt/conda/lib/python3.6/site-packages/breathe/renderer/sphinxrenderer.py", line 38, in parse_definition
    ast = parser.parse_declaration("class")
TypeError: parse_declaration() missing 1 required positional argument: 'directiveType'
```

**Comment by t-b** [comment]
Does #411 answer the question?

**Comment by sdebionne** [comment]
Oops, sorry for the duplicate and thanks for the work on Sphinx 2.0 support. Strange that Gihub "Related Issues" did not catch this obvious duplicate, really beta feature :-)
